name: CI/CD to DigitalOcean

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: my-python-app
  REGISTRY: ghcr.io/aggunr
  IMAGE_TAG: ${{ github.sha }}

jobs:
  # ---------- CI: Build and Push Docker Image ----------
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: aggunr
          password: ${{ secrets.AGGUN_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/review_classifing:${{ env.IMAGE_TAG }}

  # ---------- CD: Deploy to DigitalOcean ----------
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: ssh-keyscan -H ${{ secrets.DO_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy Docker Image
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_SERVER_IP }} "
            cd /root/home/${{ secrets.DO_USER }}/my-python-app &&
            # Update image tag in docker-compose.yamlreview_classifing
            sed -i 's|image:.*|image: ${{ env.REGISTRY }}/review_classifing:${{ env.IMAGE_TAG }}|' docker-compose.yaml &&
            docker-compose pull &&
            docker-compose down &&
            docker-compose up -d
          "
